apiVersion: v1
kind: Secret
metadata:
    name: newt-credentials
    namespace: newt
type: Opaque
stringData:
    NEWT_ID: df5sqymzby6iexp
    NEWT_SECRET: ue30nkprzqcvcoe1qswstjwrck47y9k6crwb660cofn9q9gs
