apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-wildcard-cert-iberu.me
  namespace: letsencrypt-wildcard-cert
spec:
  secretName: letsencrypt-wildcard-cert-iberu.me 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "iberu.me"
    - "*.iberu.me"