apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:XIbl4G9kCTiusYdMB9WXue0vwvuOyaFsEt0T1fWgPkdxDDMJbnPBXw==,iv:xD3t5l/l4b3QxpNbBmTx4nlVbfvdsKU8LRWT0XUHpEs=,tag:J3KKDY2GuUh1SOXSoO13HA==,type:str]
sops:
    age:
        - recipient: age1el6gjkfc3hz7u9ca6gxftsjzv266qj4j52qt2ug2f06q4latuaaqd8q0q2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMXBhYmpxME9DcC9zcFIz
            T3ZLYkJGV3hPc3NuZnZBK0Z1OHZnOWNZcUZJCktCWDJmeHhFYlhUNlRydGkzYmVn
            bzdIOGZ3SXpvT2poNEsyT3hkTXkvUEkKLS0tIEJXY3NoUURkeFVZTGc3UENwOU03
            dks2c2ZZaGt4K3pHY3hoMTkrQ3pST00K8etFASX2ahq/uB6lEz1rRtatmrhnfGkV
            idCKADzCMKPeijFmIF5FbSopwkzyzpbBFFgMGNRDLeS//YiAYf/sgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T16:43:44Z"
    mac: ENC[AES256_GCM,data:zZHRpT9NnZwlmBO40KnJZ94Cc6kZ1TcdW98fYjjRQNYMc4cJ4zWoEJoRvyJwdFbkzifoM9btlaNDqee06pAzk/6zE5oM54N48dzk7bcdXpIUqNSxvLWfXe3lCiuDVcDQe0EDs5A3JXC+sxpsKMQ6tUUfcgsARiVS+bMOtKEkaCw=,iv:VA02LiUlduERRjDxwzBTAvu71JypHrFvFkCJeM4gREk=,tag:cvPPEjo+d7l/A9u5pxp16A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
