apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 15m
  install:
    createNamespace: false
    crds: CreateReplace
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  values:
    controller:
      hostNetwork: true
      replicaCount: 2
      service:
        type: LoadBalancer
      metrics:
        enabled: true
      admissionWebhooks:
        enabled: true
        patch:
          enabled: true