apiVersion: v1
kind: Secret
metadata:
    name: keycloak-credentials
    namespace: keycloak
type: Opaque
data:
    kc-admin-username: ENC[AES256_GCM,data:QJUSF5k=,iv:NtuYVYH6kX+SLrhfoudAVNMnJCvCHCsaMXPoxfhec+o=,tag:3TYoiYZcGk4WcrKoEnkOxA==,type:str]
    kc-admin-password: ENC[AES256_GCM,data:RkkAErAyWGJH,iv:yy2qYIxa7TYG97bu71srkbxFcLbszVWpk/cgVEvADDY=,tag:0D8X92bbRbFVGG8GHlnn8g==,type:str]
    kc-db-username: ENC[AES256_GCM,data:VPg6+SQW+gY=,iv:HlHHqoG7YO9xXr0uKA1acu2B9YeanoMPGE8dl3LtjJE=,tag:6GL9j73tNybLYbKJKYEcPA==,type:str]
    kc-db-password: ENC[AES256_GCM,data:XFdqstnSiO2JXQ==,iv:aTUaExgcfgXoWXa+6pHj25xJqMsm+g0AomPSrWiQlZg=,tag:Nz6kMwzQBvMXwPwc0hFUWw==,type:str]
sops:
    age:
        - recipient: age1el6gjkfc3hz7u9ca6gxftsjzv266qj4j52qt2ug2f06q4latuaaqd8q0q2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRDdEb09Ldlo2S3pYem1N
            bzc5dTJNS2F6bHUvWjBJNjRwbDAvNmhXWWlvCml0Z0ZlMWphRkUxSFBHenFZMHEv
            V3pLYmxkSkVGTXBwMStvZWJBcFRTU0EKLS0tIFpFZHMzREl2QUliZS9RdGhDQnRW
            VkdOZCtnb1BDV2VDUXNjTUlJTW85OFEKKad6qcbwdwsJNlCr19bLOL4QKOCFdYz/
            1SneQCuTas/EnIaXX80zfFAcWyQCK+f8Xb4q3vkSMN7Lum4jK5KvcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T15:16:41Z"
    mac: ENC[AES256_GCM,data:HgwJ/kMg1dZ9+iOYWy6ihuYxQiEyqMjC74y5HmWYs74AXg7BuyYuqrhPOBYo3uANQiRVDPfElSa8Nu6OlbURx/Z2PHXL6xrAScGhc7lcbADW+8IwUwrl79Yg1TXq1xn0sVEHNiudV6sX+vT7sNrnhiswp9Xkzy1FymXfT+O3vVk=,iv:BhXRZi87DH9IU59vN1/JHggzBbM/dYCCeRufpSsxmAY=,tag:ePELU33P38FBD310j5T20Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
