apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      version: 24.7.x 
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: keycloak
  values:
    ingress:
      enabled: true
      hostname: keycloak.iberu.me
      hostnameStrict: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      ingressClassName: nginx
      tls:
        - secretName: letsencrypt-wildcard-cert
          hosts:
          - keycloak.iberu.me