apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/infrastructure
  prune: false