apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/infrastructure/keycloak
  prune: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system