apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: letsencrypt-wildcard-cert
  namespace: flux-system
spec:
  interval: 15m
  path: ./cluster/infrastructure/letsencrypt
  dependsOn:
  - name: "cert-manager"
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system