apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/storage/local-path-provisioner
  prune: true
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system