apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: newt
  namespace: flux-system
spec:
  interval: 15m
  path: ./cluster/infrastructure/newt
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age-infrastructure
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: newt-tunnel
      namespace: newt