apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-replicator
  namespace: flux-system
spec:
  interval: 15m
  path: ./cluster/infrastructure/secret-replicator
  prune: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: secret-replicator
      namespace: secret-replicator