apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-replicator
  namespace: secret-replicator
spec:
  chart:
    spec:
      chart: secret-replicator
      version: 0.6.x
      sourceRef:
        kind: HelmRepository
        name: kiwigrid
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: secret-replicator
  values:
    image:
      repository: kiwigrid/secret-replicator
      tag: latest
      pullPolicy: IfNotPresent
    secretList: "letsencrypt-wildcard-cert"
    secretNamespace: "letsencrypt-wildcard-cert"
    rbac:
      enabled: true
    resources:
      limits:
        cpu: 50m
        memory: 20Mi
      requests:
        cpu: 20m
        memory: 20Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}