apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml
patchesStrategicMerge:
  - patches/configmap.yaml
  - patches/storageclass.yaml
  - patches/namespace.yaml