apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rancher/local-path-provisioner/deploy?ref=v0.0.26
patchesStrategicMerge:
  - patches/configmap.yaml
  - patches/storageclass.yaml
  - patches/namespace.yaml