apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config--cilium
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: cilium--cilium
      namespace: flux-system
  path: ./
  prune: true
  timeout: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: cilium
      namespace: kube-system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: cilium-envoy
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: cilium-operator
      namespace: kube-system