apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.x
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  targetNamespace: ingress-nginx
  interval: 15m
  timeout: 5m
  values:
    controller:
      hostNetwork: true
      replicaCount: 2
      service:
        type: LoadBalancer
      metrics:
        enabled: true